# Generated by Django 3.0.2 on 2020-01-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
