# Generated by Django 3.0.2 on 2020-01-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
